export const starterSetOfFavorites = [
  { name: 'Gray', value: '#212529' },
  { name: 'Red', value: '#c92a2a' },
  { name: 'Pink', value: '#a61e4d' },
  { name: 'Grape', value: '#862e9c' },
  { name: 'Violet', value: '#5f3dc4' },
  { name: 'Indigo', value: '#364fc7' },
  { name: 'Blue', value: '#1864ab' },
  { name: 'Cyan', value: '#0b7285' },
  { name: 'Teal', value: '#087f5b' },
  { name: 'Green', value: '#2b8a3e' },
  { name: 'Lime', value: '#5c940d' },
  { name: 'Yellow', value: '#e67700' },
  { name: 'Orange', value: '#d9480f' },
];
