export const starterSetOfFavorites = [
  { name: 'Angular Red', value: '#b52e31' },
  { name: 'Auth0 Orange', value: '#eb5424' },
  { name: 'Azure Blue', value: '#007fff' },
  { name: 'C# Purple', value: '#68217A' },
  { name: 'Gatsby Purple', value: '#639' },
  { name: 'Go Cyan', value: '#5dc9e2' },
  { name: 'Java Blue-Gray', value: '#557c9b' },
  { name: 'JavaScript Yellow', value: '#f9e64f' },
  { name: 'Mandalorian Blue', value: '#1857a4' },
  { name: 'Node Green', value: '#215732' },
  { name: 'React Blue', value: '#00b3e6' },
  { name: 'Something Different', value: '#832561' },
  { name: 'Vue Green', value: '#42b883' },
  { name: 'Svelte Orange', value: '#ff3e00' },
];
